import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "How bad are PFAS affecting us?",
  "subtitle": "As of 2022, 57% of all monitored sites across surface water bodies in the EU exceed the annual average environmental quality standards (EQS) for PFOS.",
  "colourSchemeClasses": 7,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nAustria,AT,null,TRUE,74 µg/kg in Austrian breadcrumbs,,,,,,,,\nBelgium,BE,1,TRUE,340 µg/kg in Belgian wholemeal bread,,,,,,,,\nBulgaria,BG,0.0526,True,49 µg/kg in Bulgarian biscuits,,,,,,,,\nCyprus,CY,null,false,,,,,,,,,\nCzechia,CZ,1,true,42 µg/kg in a Czech poppy seed bun,,,,,,,,\nGermany,DE,0.8315,true,310 µg/kg in wheat flour (produced in Germany),,,,,,,,\nDenmark,DK,null,FALSE,,,,,,,,,\nEstonia,EE,0.022,FALSE,,,,,,,,,\nGreece,EL,null,true,17 µg/kg in Greek rusks with olive oil,,,,,,,,\nSpain,ES,0.1818,true,120 µg/kg in Spanish toasting bread,,,,,,,,\nFinland,FI,0,FALSE,,,,,,,,,\nFrance,FR,1,true,210 µg/kg in a French baguette,,,,,,,\nCroatia,HR,0.000,FALSE,,,,,,,,,\nHungary,HU,null,true,31 µg/kg in Hungarian coarse oat flakes,,,,,,,,\nIreland,IE,0.0588,FALSE,,,,,,,,,\nItaly,IT,0.537,true,26 µg/kg in Italian spaghetti ,,,,,,,,\nLithuania,LT,null,FALSE,,,,,,,,,\nLuxembourg,LU,null,FALSE,,,,,,,,,\nLatvia,LV,0,FALSE,,,,,,,,,\nMalta,MT,null,FALSE,,,,,,,,,\nNetherlands,NL,0.963,true,130 µg/kg in Dutch gingerbread (pepernoten),,,,,,,,\nPoland,PL,0.0488,true,62 µg/kg in Polish spelt toast bread,,,,,,,,\nPortugal,PT,1,true,Data from 2018 and only one monitored site,,,,,,,,\nRomania,RO,0.090,true,49 µg/kg in corn flour from Romania,,,,,,,,\nSweden,SE,0.4,FALSE,,,,,,,,,\nSlovenia,SI,null,FALSE,,,,,,,,,\nSlovakia,SK,null,FALSE,,,,,,,,,",
  "parsedData": [
    {
      "country": "Austria",
      "id": "AT",
      "value": null,
      "extraInfo": true,
      "text_content": "74 µg/kg in Austrian breadcrumbs",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Belgium",
      "id": "BE",
      "value": 1,
      "extraInfo": true,
      "text_content": "340 µg/kg in Belgian wholemeal bread",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 0.0526,
      "extraInfo": true,
      "text_content": "49 µg/kg in Bulgarian biscuits",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": null,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 1,
      "extraInfo": true,
      "text_content": "42 µg/kg in a Czech poppy seed bun",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 0.8315,
      "extraInfo": true,
      "text_content": "310 µg/kg in wheat flour (produced in Germany)",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": null,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 0.022,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": null,
      "extraInfo": true,
      "text_content": "17 µg/kg in Greek rusks with olive oil",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 0.1818,
      "extraInfo": true,
      "text_content": "120 µg/kg in Spanish toasting bread",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 1,
      "extraInfo": true,
      "text_content": "210 µg/kg in a French baguette",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": null,
      "extraInfo": true,
      "text_content": "31 µg/kg in Hungarian coarse oat flakes",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 0.0588,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 0.537,
      "extraInfo": true,
      "text_content": "26 µg/kg in Italian spaghetti",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": null,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": null,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": null,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 0.963,
      "extraInfo": true,
      "text_content": "130 µg/kg in Dutch gingerbread (pepernoten)",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 0.0488,
      "extraInfo": true,
      "text_content": "62 µg/kg in Polish spelt toast bread",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 1,
      "extraInfo": true,
      "text_content": "Data from 2018 and only one monitored site",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 0.09,
      "extraInfo": true,
      "text_content": "49 µg/kg in corn flour from Romania",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 0.4,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": null,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": null,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "percent",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "red",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": false,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "European Environmental Agency (2022)",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "For groundwater, no EU EQS is specified only values for surface water is visualized. Trifluoroacetic acid (TFA) is a highly persistent degradation product of other PFAS, including some pesticides, and can remain in surface and groundwater for long periods. PFOS is a priority substance under the EU Water Framework Directive, with environmental quality standards of 0.65 ng/l for inland surface waters, 0.13 ng/l for coastal and transitional waters, and 9.1 µg/kg (wet weight) for biota.\nNo data for Austria, Cyprus, Denmark, Greece, Hungary, Lithuania, Luxembourg, Malta, Slovenia, Slovakia.",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://www.eea.europa.eu/en/analysis/publications/pfas-pollution-in-european-waters",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": true,
  "customUnitLabel": "of monitored sites exceed PFOS EQS",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "How bad are PFAS affecting us?",
    "subtitle": "As of 2022, 57% of all monitored sites across surface water bodies in the EU exceed the annual average environmental quality standards (EQS) for PFOS.",
    "textNoteDescription": "Note",
    "textNote": "For groundwater, no EU EQS is specified only values for surface water is visualized. Trifluoroacetic acid (TFA) is a highly persistent degradation product of other PFAS, including some pesticides, and can remain in surface and groundwater for long periods. PFOS is a priority substance under the EU Water Framework Directive, with environmental quality standards of 0.65 ng/l for inland surface waters, 0.13 ng/l for coastal and transitional waters, and 9.1 µg/kg (wet weight) for biota.\nNo data for Austria, Cyprus, Denmark, Greece, Hungary, Lithuania, Luxembourg, Malta, Slovenia, Slovakia.",
    "textSourceDescription": "Source",
    "textSource": "European Environmental Agency (2022)",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here",
    "extraInfo_AT": "74 µg/kg in Austrian breadcrumbs",
    "extraInfo_BE": "340 µg/kg in Belgian wholemeal bread",
    "extraInfo_BG": "49 µg/kg in Bulgarian biscuits",
    "extraInfo_CZ": "42 µg/kg in a Czech poppy seed bun",
    "extraInfo_DE": "310 µg/kg in wheat flour (produced in Germany)",
    "extraInfo_EL": "17 µg/kg in Greek rusks with olive oil",
    "extraInfo_ES": "120 µg/kg in Spanish toasting bread",
    "extraInfo_FR": "210 µg/kg in a French baguette",
    "extraInfo_HU": "31 µg/kg in Hungarian coarse oat flakes",
    "extraInfo_IT": "26 µg/kg in Italian spaghetti",
    "extraInfo_NL": "130 µg/kg in Dutch gingerbread (pepernoten)",
    "extraInfo_PL": "62 µg/kg in Polish spelt toast bread",
    "extraInfo_PT": "Data from 2018 and only one monitored site",
    "extraInfo_RO": "49 µg/kg in corn flour from Romania"
  },
  "clusters": [],
  "colorScale": null,
  "extraInfo_AT": "74 µg/kg in Austrian breadcrumbs",
  "extraInfo_BE": "340 µg/kg in Belgian wholemeal bread",
  "extraInfo_BG": "49 µg/kg in Bulgarian biscuits",
  "extraInfo_CZ": "42 µg/kg in a Czech poppy seed bun",
  "extraInfo_DE": "310 µg/kg in wheat flour (produced in Germany)",
  "extraInfo_EL": "17 µg/kg in Greek rusks with olive oil",
  "extraInfo_ES": "120 µg/kg in Spanish toasting bread",
  "extraInfo_FR": "210 µg/kg in a French baguette",
  "extraInfo_HU": "31 µg/kg in Hungarian coarse oat flakes",
  "extraInfo_IT": "26 µg/kg in Italian spaghetti",
  "extraInfo_NL": "130 µg/kg in Dutch gingerbread (pepernoten)",
  "extraInfo_PL": "62 µg/kg in Polish spelt toast bread",
  "extraInfo_PT": "Data from 2018 and only one monitored site",
  "extraInfo_RO": "49 µg/kg in corn flour from Romania"
});